add backup file
GuskovAlexey/homework pull request #3
Opened 2022-09-16 09:47 UTC by GuskovAlexey

2022-09-16 18:53 UTC, drempost requested changes
в backup.sh надо доработать, чтобы пороги считывало
в monitoring нужно немного поработать еще с данными
time хорошо

2022-09-16 18:53 UTC, drempost commented on bash/backup.sh
> +PATH=/etc:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
а зачем?)

2022-09-16 18:53 UTC, drempost commented on bash/backup.sh
> +source="/home/lespot/homework"
в эти переменные надо добавить входные параметры скрипта $1 и тд

2022-09-16 18:53 UTC, drempost commented on bash/backup.sh
> +destination_root="/backup"
$2

2022-09-16 18:53 UTC, drempost commented on bash/backup.sh
> +  tar zcf ${destination_root}/archive/samba_${fdate}.tar.gz ./*
нужно добавить еще переменную порога количества бэкапов и удалять последние, если больше порога, порог задается как 3ий входной параметр скрипта

2022-09-16 18:53 UTC, drempost commented on bash/monitoring.sh
> +# show process
чуть-чуть надо еще поиграться с данными, чтобы соответствовало ТЗ

2022-09-17 14:06 UTC, GuskovAlexey commented on bash/backup.sh
> +PATH=/etc:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
а хз... убрал)

2022-09-17 14:10 UTC, GuskovAlexey commented on bash/monitoring.sh
> +# show process
переделал полностью файл мониторинг

2022-09-17 14:30 UTC, GuskovAlexey commented on bash/backup.sh
> +source="/home/lespot/homework"
Сделать source=$1 чтоб при старте скрипта я указывал папку которую нужно бэкапить?

2022-09-19 13:28 UTC, drempost commented on bash/backup.sh
> +source="/home/lespot/homework"
да

2022-09-19 13:34 UTC, drempost approved these changes
в целом, уже норм, есть некоторые мелочи, но их лучше попровить, чтобы код был понятнее/чище, а так можно мерджить

2022-09-22 16:26 UTC, GuskovAlexey commented
End lesson 9-10-11

2022-09-22 16:26 UTC, GuskovAlexey commented
End lesson 9-10-11

2022-09-22 16:27 UTC, merged